# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sam_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sam_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sam_service.proto\x12\x03sam\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"x\n\x04Mask\x12\x12\n\nmask_array\x18\x01 \x01(\x0c\x12\x0c\n\x04\x61rea\x18\x02 \x01(\x02\x12\x1e\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x10.sam.BoundingBox\x12\x15\n\rpredicted_iou\x18\x04 \x01(\x02\x12\x17\n\x0fstability_score\x18\x05 \x01(\x02\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"h\n\x0cMaskResponse\x12\x18\n\x05masks\x18\x01 \x03(\x0b\x32\t.sam.Mask\x12\x14\n\x0cimage_height\x18\x02 \x01(\x05\x12\x13\n\x0bimage_width\x18\x03 \x01(\x05\x12\x13\n\x0btotal_masks\x18\x04 \x01(\x05\x32\x42\n\nSAMService\x12\x34\n\x0cProcessImage\x12\x11.sam.ImageRequest\x1a\x11.sam.MaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sam_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=26
  _globals['_IMAGEREQUEST']._serialized_end=60
  _globals['_MASK']._serialized_start=62
  _globals['_MASK']._serialized_end=182
  _globals['_BOUNDINGBOX']._serialized_start=184
  _globals['_BOUNDINGBOX']._serialized_end=250
  _globals['_MASKRESPONSE']._serialized_start=252
  _globals['_MASKRESPONSE']._serialized_end=356
  _globals['_SAMSERVICE']._serialized_start=358
  _globals['_SAMSERVICE']._serialized_end=424
# @@protoc_insertion_point(module_scope)
